#!/usr/bin/env python
"""Extract data from an specified GeoNode

Usage:

geonode-extract http://example.geonode.com -d <dest_dir>
"""
import sys
import extract

print "Running geonode-extract v%s" % extract.__version__

extract.run(sys.argv)
