#!/usr/bin/env python
"""Extract data from an specified GeoNode

Usage:

geonode-extract http://example.geonode.com -d <dest_dir>
"""
import sys
import extract

print 'Running geonode-extract v%s' % extract.__version__

if len(sys.argv) < 2:
    print 'Usage:\n geonode-extract http://example.geonode.com'
    sys.exit(-1)

host = sys.argv[1]

options = {}
if len(sys.argv) > 3:
    assert(sys.argv[2] == '-d')
    options['dest_dir'] = sys.argv[3]

extract.get_data(host, **options)
