#!/usr/bin/env python
"""Extract data from an specified GeoNode

Usage:

geonode-extract http://example.geonode.com -d <dest_dir>
"""
import sys
import extract

print 'Running geonode-extract v%s' % extract.__version__

host = sys.argv[1]

options = {}
if len(sys.argv) > 2:
    options['dest_dir'] = sys.argv[2]

extract.get_data(host, options*)
